---  # yaml document beginning
# This is the config.yaml file for the MTDPolicy Framework

#key: value
appname: MTDPolicy



# all options:
options:
  WINDOWS: [30, 60, 120, 150, 180, 300, 360]
  FUNCTIONS: ['mean', 'max', 'min']
  infected: [1, 2, 4, 5,] # positions of the infected datasets
  healthy: [0] # position of the healthy dataset


# set options
windows: [30, 60, 120, 150, 180, 300, 360] # number of datapoints of the non-overlapping windows
infected: [0, 1, 5, 6, 7, 8, 9] # positions of the infected datasets
healthy: [2] # position of the healthy dataset
functions: ['mean'] # aggragation functions


# policy creation
## general
windowSize: 360 # define the window size for which the policy should be generated
aggregateFunctions: ['mean', 'min', 'max']

seed: 10 # random seed to obtain the same policies in the random approach
randomPolicyCreation: False # enable random policy creation
randomNumberOfPolicyRules: False 
maxNumberOfPolicyRules: 6
minNumberOfPolicyRules: 3
exactNumberOfPolicyRules: 4

completePolicyCreation: True # enable complete policy creation

expertPolicyCreation: False

#
threshholds: [1, 3, 5]

# policy selection
interval: 60
countMalwareIndicators: False
countMalwareTypeIndicators: False
countMalwareIndicatorsRelatively: True
modes:
- name: sensitive
  letter: S
  detectionTreshold: 0.05
- name: average
  letter: A
  detectionTreshold: 0.05
- name: robust
  letter: R
  detectionTreshold: 0.80
mode:
- name: robust
  letter: R
  detectionTreshold: 0.60


dstatCommand: ['dstat', '-t', '--cpu', '--mem', '--fs', '-d', '--disk-tps', '-n', '--tcp', '-y', '-p', '-N', 'eth0', '1', '11']
ipFinderCommand: ['hostname', '-I']