---
# This is the config file for the MTD Strategy Selection Agent StraSelA
appname: MTD Strategy Selection Agent

# GENERAL
ipFinderCommand: ['hostname', '-I']
dstatCommand: ['dstat', '-t', '--cpu', '--mem', '--fs', '-d', '--disk-tps', '-n', '--tcp', '--socket','-y', '-p', '-N', 'eth0', '1', '11']

# PARAMETERS
historyLen: 10
detectionThreshold: 0.6
evaluationMethod: 2 # 0: sort by #pos, 2: sort by %

# MTD COMMANDS
ransomwareMTD: 'python3 /root/MTDStrategySelectionAgent/agent/MTD/Ransomware/CreateDummyFiles.py --path=/root/sample-data --numberOfDummyFiles=30 --numberOfDummyFilesPerSubdirectory=15 --size=10 --extension=pdf'
cncMTD: 'python3 /root/MTDStrategySelectionAgent/agent/MTD/CnC/ChangeIpAddress.py'
rootkitMTD: 'python3 /root/MTDStrategySelectionAgent/agent/MTD/Rootkit/RemoveRootkit.py'